import PropTypes from 'prop-types'
import Head from 'next/head'
import { ThemeProvider } from 'styled-components'
import theme from '../styles/theme'
import GlobalStyles from '../styles/globals'
import Navbar from '../components/Navbar'
import ContextProvider from '../provider/PlansContext'
import PaymentManager from '../provider/PaymentContext'

function App({ Component, pageProps }) {
  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Afya Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <GlobalStyles />
      <Navbar />
      <ContextProvider>
        <PaymentManager>
          <Component {...pageProps} />
        </PaymentManager>
      </ContextProvider>
    </ThemeProvider>
  )
}

App.propTypes = {
  Component: PropTypes.node,
  pageProps: PropTypes.object
}

export default App
